### ISSUE TITLE
Function parameters in destructed object are not trimmed

### ISSUE THREAD

**Issue by kristofferkarlsson93** [arrizalamin/js-function-reflector#16]
Hi! 
Found a strange behaviour.

When using the function reflector on a function that looks like this (each parameter chopped down on new line)

```javascript
module.exports = function ({
    param1,
    param2
}) {}
```

and extract the parameters in the parameterobject like this 

```javascript
const reflector = functionReflector(module);
return reflector.params[0].value.keys[0].name
```

it returns the parameter with an \r (windows new line character) in the begining and end.  `\rparam1\r`

I solved this by using .trim(). But perhaps it is good for you to know.

**Comment by arrizalamin** [comment]
Hi! Thanks for the report, this is fixed in c1485c1. Please update to version `2.0.3`.
