### ISSUE TITLE
Doesn't reflect async functions compiled with babel 

### ISSUE THREAD

**Issue by atheros** [arrizalamin/js-function-reflector#2]
Unless I'm doing something wrong, reflecting async functions compiled with babel's babel-plugin-transform-async-to-generator

Input is:

```
    async (ms = 1000) => {
        let delay = require('await-delay');
        await delay(typeof ms == 'string' ? parseInt(ms, 10) : ms);
    }
```

Result is:

```
{ name: 'anonymous',
  args: [ '_x' ],
  body: 'return _ref.apply(this, arguments);' }
```

Tested on node 6.4.0

**Comment by arrizalamin** [comment]
async function was not in ES6 proposal. I will add this in the next major version. meanwhile use ES6 promise chain.
