### ISSUE TITLE
not working if default parameter is filled array or object

### ISSUE THREAD

**Issue by leonardiwagner** [arrizalamin/js-function-reflector#3]
```javascript
var functionReflector = require('js-function-reflector')
functionReflector((a = true, b = [1, 2, 3], c = {a: 1, b: 2, c: 3 }) => { })
```

returns 

```javascript
{ name: 'anonymous',
  args: 
   [ [ 'a', true ], // correct
     [ 'b', 'var([1)' ], '2','3]',  // wrong
     [ 'c', 'var({a:1)' ], 'b:2','c:3}' ] // wrong,
  body: '' }
```

on `get-name-and-arguments.js` the whitespace regex doesn't do the work well 😢 

<img width="528" alt="screen shot 2017-04-18 at 18 30 41" src="https://cloud.githubusercontent.com/assets/2164551/25154057/5c39683a-2465-11e7-9943-5c3c3a2926e5.png">

**Comment by arrizalamin** [comment]
thanks, I think parameters should be split with parser and stack instead of just splitting it with a comma.
