### ISSUE TITLE
A different approach for parser

### ISSUE THREAD

**Issue by bySabi** [arrizalamin/js-function-reflector#7]
@arrizalamin I open a issue to continue discussion: https://github.com/z-pattern-matching/z/issues/23

> @bySabi the idea is when a parser finds a string opening (',",`) it will scan until the end of a string and parse that as a string. When it finds a number, use parseFloat() to parse them as a number. We need to make the same thing for regex/symbol/etc. And when it finds an object/array opening ({,[), it will scan all key as a string and all of the previous functions (string,number,regex,etc) to parse the value recursively and rebuilt that object/array with all of the parsed keys and values.

What do you do when you found this string `"MyCustomType"`?  how you rehydrate it? ... That's the wall I'm talking about.

IMO parse all values and built-in's it is too much work and is slow. This can be simple like:
```
const  valueStr = "[ { level1: [ { level2: { level3: [ Object,  Promise , { deepest: 777 }] }}]}]"
const deserializer = str => Function('return ' + str)()

const value = deserializer(valueStr)
console.log(value[0].level1[0].level2.level3[2].deepest === 777)  // true
```

But it you need deserialze **not global**  types. You will need set it in a context, Ex:
```
class CustomType {}

const  valueStr = "[ { level1: [ { level2: { level3: [ Object,  Promise , { deepest: CustomType }] }}]}]"
const deserializer = (str,ctx) => Function(`
  const { CustomType } = this
  return ${str}
`).call(ctx)

const value = deserializer(valueStr, { CustomType })
console.log(value[0].level1[0].level2.level3[2].deepest === CustomType)  // true
```

or Use the first snippet and put CustomType in global, say:
```
global.CustomType = CustomType 
```

Maybe this will be fine for your users and is a matter of convention adding the global trick to Doc. 

In my case, `pattern-matching` I will not follow this path cause is not needed if we accept a little different sintax than orginal use by `z`

**Comment by arrizalamin** [comment]
Hi @bySabi, sorry for a very late response. I already replaced `eval` with `Function()` in #15, thanks for your suggestion.
